force-app/main/default/objects/Battery__c/Battery__c.object-meta.xml
<CustomObject>
    <label>Battery</label>
    <nameField>
        <displayFormat>BAT-{0000}</displayFormat>
        <label>Battery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batteries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Battery__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <description>Production batch</description>
    <label>Batch Number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Battery_Model__c.field-meta.xml
<CustomField>
    <fullName>Battery_Model__c</fullName>
    <description>Product model</description>
    <label>Battery Model</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Battery_PIN__c.field-meta.xml
<CustomField>
    <fullName>Battery_PIN__c</fullName>
    <description>Unique Battery ID</description>
    <label>Battery PIN</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Location</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Batteries</relationshipLabel>
    <relationshipName>Batteries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Battery__c/fields/FIFO_Eligible__c.field-meta.xml
<CustomField>
    <fullName>FIFO_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIFO Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Manufacturing_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Date__c</fullName>
    <description>Production date</description>
    <label>Manufacturing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Battery__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Encoded QR information</description>
    <label>QR Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Unique serial</description>
    <label>Serial Number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Battery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the current lifecycle status of the battery</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Produced</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Warehouse_Received</fullName>
                <label>Warehouse Received</label>
            </value>
            <value>
                <fullName>In Warehouse</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatteryFifoController.cls
public with sharing class BatteryFifoController {

    @AuraEnabled(cacheable=true)
    public static List<Battery__c> getFifoStock(
        Id warehouseId,
        String batchNumber
    ) {

        String query =
            'SELECT Id, Name, Battery_PIN__c, QR_Code__c, ' +
            'Serial_Number__c, Battery_Model__c, ' +
            'Batch_Number__c, Manufacturing_Date__c, ' +
            'Status__c, Inventory_Status__c, ' +
            'Current_Location__c, FIFO_Eligible__c, CreatedDate ' +
            'FROM Battery__c ' +
            'WHERE Inventory_Status__c = \'Available\' ' +
            'AND FIFO_Eligible__c = true ';

        // Temporarily DON'T filter warehouse
        // until Current_Location lookup is corrected.

        if (String.isNotBlank(batchNumber)) {
            query += 'AND Batch_Number__c = :batchNumber ';
        }

        query +=
            'ORDER BY Manufacturing_Date__c ASC, CreatedDate ASC';

        System.debug('FIFO Query => ' + query);

        List<Battery__c> batteries = Database.query(query);

        System.debug('FIFO Batteries => ' + batteries);

        return batteries;
    }
}